- name: Update packages cache
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove all conflicting packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  ignore_errors: true

- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create keyrings directory
  file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: "0755"

- name: Download Docker GPG
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Get system architecture
  command: bash -c "dpkg --print-architecture"
  register: system_arch

- name: Get Ubuntu codename
  command: bash -c ". /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\""
  register: codename

- name: Add the repository to apt sources
  copy:
    content: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ codename.stdout }} stable"
    dest: /etc/apt/sources.list.d/docker.list

- name: Update packages cache after adding Docker repo
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Docker latest version
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
